sonar.projectKey=sonarqube-generic-test
sonar.projectName=SonarQube Generic Test
sonar.projectVersion=1.0

sonar.terraform.file.suffixes=.tf,.hcl,.tfvars
sonar.python.file.suffixes=.py



# Enabling debug/verbose logging
sonar.verbose=true
sonar.log.level=DEBUG

# Define source and test locations explicitly
sonar.sources=.
sonar.tests=.
sonar.inclusions=src/**/*.py,terraform/main.tf
sonar.test.inclusions=tests/**/*.py,terraform/tests/**/*.tf

# Exclusions
sonar.exclusions=reports/**,generate_reports.py,docker-compose.yml

sonar.python.version=3

# Generic Reports
sonar.testExecutionReportPaths=reports/test-results.xml
sonar.coverageReportPaths=reports/coverage.xml

sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
#sonar.token=REDACTED_USE_YOUR_OWN_TOKEN
sonar.token=${SONAR_TOKEN}
