sonar.projectKey=sonarqube-generic-test
sonar.projectName=SonarQube Generic Test
sonar.projectVersion=1.0

# Enabling debug/verbose logging
sonar.verbose=true
sonar.log.level=DEBUG

# Define source and test locations explicitly
sonar.sources=.
sonar.tests=.
sonar.inclusions=src/**/*.py,terraform/main.tf
sonar.test.inclusions=tests/**/*.py,terraform/tests/**/*.tf

# Exclusions
sonar.exclusions=reports/**,generate_reports.py,docker-compose.yml

sonar.python.version=3

# Generic Reports
sonar.testExecutionReportPaths=reports/test-results.xml
sonar.coverageReportPaths=reports/coverage.xml

sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.token=squ_a15d4dd374f872dce12d35f51cbd6970d9dd0722
