sonar.projectKey=sonarqube-generic-test
sonar.projectName=SonarQube Generic Test
sonar.projectVersion=1.0

sonar.terraform.file.suffixes=.tf,.hcl,.tfvars
sonar.python.file.suffixes=.py



# Enabling debug/verbose logging
sonar.verbose=true
sonar.log.level=DEBUG

# Define source and test locations explicitly
sonar.sources=.
sonar.tests=.

# Source File Inclusions - specify patterns for source files
sonar.inclusions=src/**/*.py,terraform/**/*.tf,core-cloud-s3-tf-module/**/*.tf

# Test File Inclusions - specify patterns for test files
sonar.test.inclusions=./**/tests/**/*.py,./**/tests/**/*.tftest.hcl

# Source File Exclusions - ignore test fixtures, generated reports, and common Python cache files
sonar.exclusions=reports/**,generated/**,**/__pycache__/**,**/*.pyc,**/*.pyo,**/*.pyd,./**/.venv/**/*

# Test File Exclusions - ignore common Python cache files in test directories
sonar.test.exclusions=**/__pycache__/**,**/*.pyc,**/*.pyo,**/*.pyd,./**/.venv/**/*

sonar.python.version=3

# Generic Reports
sonar.testExecutionReportPaths=reports/test-results.xml,generated/*.sonar.xml
sonar.coverageReportPaths=reports/coverage.xml

sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
#sonar.token=REDACTED_USE_YOUR_OWN_TOKEN
sonar.token=${SONAR_TOKEN}
